### ISSUE TITLE
Add rocBLAS support

### ISSUE THREAD

**Issue by minus1ms** [Axect/Peroxide_BLAS#1]
Hi, i have the AMD GPU and im wondering if there is a way to implement rocBLAS support for this crate... its a suggestion

**Comment by Axect** [comment]
Hello, @minus1ms 

Thank you for your interest in Peroxide and for suggesting rocBLAS support. I appreciate your idea as it opens up interesting possibilities for future expansion. 

I want to clarify that this repository is actually an example for Peroxide's O3 functionality, and the main Peroxide repository can be found at github.com/Axect/Peroxide. While I don't currently have plans to implement GPU support myself, I'm certainly open to the possibility of GPU support as a future extension.

If you or anyone else is interested in implementing rocBLAS support, you're more than welcome to contribute. You could start by opening a new issue in the main Peroxide repository to discuss the feature in detail. If we agree it's a good direction, I'd be happy to create a feature branch for the implementation. You could then work on it and submit a pull request when ready.

As an open-source project, Peroxide thrives on community contributions, so please feel free to get involved if you're passionate about this feature. Your interest in improving Peroxide is truly appreciated, and I'm excited to see how we might expand the library's capabilities in the future. Thank you again for your suggestion!
